[build-system]
requires = ["setuptools>=69.0.2", "wheel>=0.42.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pg-material-tracker"
version = "1.0.0"
description = "Construction Material Tracking System"
requires-python = ">=3.12"
